module Akane
  class Emulator
    CYCLES_PER_FRAME: Integer

    def self.start: (CLI::emulator_options options) -> void
    def self.advance_components: () -> void
    def self.stop: () -> void
  end
end
